#!/usr/bin/env node
// Copies the vendored receipt schema (oss/sdk-js/src/receipt.schema.json) into this package's
// src/ so it can be bundled and imported at runtime, without this package ever reading outside
// oss/sdk-js. The vendored copy at oss/sdk-js root is the synced source of truth — never edit it
// here; this script only copies bytes.
import { copyFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, "..", "..", "..", "src", "receipt.schema.json");
const destDir = join(here, "..", "src", "generated");
const dest = join(destDir, "receipt.schema.json");

mkdirSync(destDir, { recursive: true });
copyFileSync(src, dest);

// Also emit a TS module embedding the schema as a JS object literal, so packages/sdk/dist never
// needs a runtime JSON import (import assertions vary across Node/Deno/bundlers) or `fs`.
import { readFileSync, writeFileSync } from "node:fs";
const schemaText = readFileSync(src, "utf-8");
const schemaObj = JSON.parse(schemaText);
const tsOut = join(destDir, "receipt-schema.ts");
writeFileSync(
  tsOut,
  `/**\n * This file is generated by scripts/copy-schema.mjs from ../../../src/receipt.schema.json\n * (the vendored PoAW receipt schema, synced from oss/spec). Do not edit by hand.\n */\nexport const receiptSchema = ${JSON.stringify(schemaObj, null, 2)} as const;\n`,
);
console.log(`copied ${src} -> ${dest} and ${tsOut}`);
