#!/usr/bin/env node
// Copies the vendored schemas (oss/sdk-js/src/{receipt,change,pipeline}.schema.json) into this package's
// src/generated/ so they can be bundled and imported at runtime, without this package ever reading outside
// oss/sdk-js. The vendored copies at oss/sdk-js root are the synced source of truth — never edit them
// here; this script only copies bytes.
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const destDir = join(here, "..", "src", "generated");
mkdirSync(destDir, { recursive: true });

// Also emit a TS module embedding each schema as a JS object literal, so packages/sdk/dist never
// needs a runtime JSON import (import assertions vary across Node/Deno/bundlers) or `fs`.
for (const name of ["receipt", "change", "pipeline"]) {
  const src = join(here, "..", "..", "..", "src", `${name}.schema.json`);
  const dest = join(destDir, `${name}.schema.json`);
  copyFileSync(src, dest);
  const schemaObj = JSON.parse(readFileSync(src, "utf-8"));
  const tsOut = join(destDir, `${name}-schema.ts`);
  writeFileSync(
    tsOut,
    `/**\n * This file is generated by scripts/copy-schema.mjs from ../../../src/${name}.schema.json\n * (the vendored PoAW ${name} schema, synced from oss/spec). Do not edit by hand.\n */\nexport const ${name}Schema = ${JSON.stringify(schemaObj, null, 2)} as const;\n`,
  );
  console.log(`copied ${src} -> ${dest} and ${tsOut}`);
}
