#!/usr/bin/env node
// Generates packages/sdk/src/generated/receipt.ts from the vendored receipt.schema.json.
// Run via `npm run gen:types`. The output is committed; `test/generated-types.test.ts` regenerates
// it in memory and fails on drift.
import { writeFileSync, readFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { compile } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const schemaPath = join(here, "..", "..", "..", "src", "receipt.schema.json");
const outPath = join(here, "..", "src", "generated", "receipt.ts");

export async function generate() {
  const schema = JSON.parse(readFileSync(schemaPath, "utf-8"));
  const ts = await compile(schema, "Receipt", {
    additionalProperties: false,
    bannerComment:
      "/* eslint-disable */\n/**\n * This file was automatically generated by `npm run gen:types` from\n * ../../../src/receipt.schema.json (the vendored PoAW receipt schema). Do not edit by hand.\n */",
    style: { singleQuote: false },
  });
  return ts;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const ts = await generate();
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, ts);
  console.log(`wrote ${outPath}`);
}
