#!/usr/bin/env node
// Generates packages/sdk/src/generated/{receipt,change,pipeline}.ts from the vendored schemas.
// Run via `npm run gen:types`. The output is committed; `test/generated-types.test.ts` regenerates
// it in memory and fails on drift.
import { writeFileSync, readFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { compile } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const NAMES = { receipt: "Receipt", change: "Change", pipeline: "Pipeline" };

export async function generateFor(name) {
  const schema = JSON.parse(readFileSync(join(here, "..", "..", "..", "src", `${name}.schema.json`), "utf-8"));
  return compile(schema, NAMES[name], {
    additionalProperties: false,
    bannerComment: `/* eslint-disable */\n/**\n * This file was automatically generated by \`npm run gen:types\` from\n * ../../../src/${name}.schema.json (the vendored PoAW ${name} schema). Do not edit by hand.\n */`,
    style: { singleQuote: false },
  });
}

/** The receipt types (kept for the existing drift test). */
export const generate = () => generateFor("receipt");

if (import.meta.url === `file://${process.argv[1]}`) {
  const dir = join(here, "..", "src", "generated");
  mkdirSync(dir, { recursive: true });
  for (const name of Object.keys(NAMES)) {
    const outPath = join(dir, `${name}.ts`);
    writeFileSync(outPath, await generateFor(name));
    console.log(`wrote ${outPath}`);
  }
}
